# Generated by Django 6.0.4 on 2026-05-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_category_otprequest_appointment_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='booking_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed booking amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for receiving payments', max_length=100, null=True),
        ),
    ]
